lifeart/glimmer-next

src/components/Application.ts, src/components/Row.ts, src/components/Smile.ts, src/index.ts, src/utils/component.ts, src/utils/dom.ts, src/utils/if.ts, src/utils/list.ts, src/utils/reactive.ts, src/utils/runtime.ts, src/utils/vm.ts, tsconfig.json
https://github.com/lifeart/glimmer-next/assets/1360552/f2592b27-2803-4745-931e-b93a65a66aee
=> Async destructors

package.json, plugins/compiler.ts, pnpm-lock.yaml, src/index.ts, src/utils/component.ts, src/utils/dom.ts, src/utils/ember-inspector.ts, src/utils/if.ts, src/utils/inspector/index.ts, src/utils/list.ts, src/utils/reactive.ts, src/utils/shared.ts, src/utils/vm.ts, tsconfig.json, types/index.d.ts, vite.config.mts
=> ember inspector support

.github/workflows/perf.yml, .gitignore, .npmignore, bin/setup-bench.mjs, package.json, pnpm-lock.yaml
=> Tracerbench setup

.github/workflows/perf.yml, README.md, bin/setup-bench.mjs, package.json, plugins/test.ts, pnpm-lock.yaml, src/components/Application.gts, src/index.ts, src/utils/component.ts, src/utils/dom.ts, src/utils/index.ts, src/utils/reactive.ts, tsconfig.json, vite.config.mts
Adding `@tracked` decorator here, thanks to @ef4 for https://github.com/ef4/decorator-transforms and @NullVoxPopuli for idea.
To use it in app, users need to add this import in top-level file:
```
import "decorator-transforms/globals";
```
=> tracked decorator

src/tests/integration/each-test.gts, src/tests/utils.ts
Some are actually failing! 😱
I might have made wrong assumptions so don't hesitate to tell me what to change.
=> Add tests for each loop

plugins/converter.test.ts, plugins/flags.ts, plugins/utils.ts, src/components/Application.gts, src/components/pages/Benchmark.gts, src/components/pages/benchmark/Row.gts, src/tests/integration/bare-functions-test.gts, src/tests/integration/bare-test.gts, src/tests/integration/if-test.gts, src/utils/dom.ts
This is experiment PR to see performance differences with glimmer reactivity compatibility and granular reactivity
=> [bench] without glimmer compat logic

src/components/pages/Router.gts, src/utils/component.ts, src/utils/dom-api.ts, src/utils/dom.ts, src/utils/if.ts, src/utils/list.ts, src/utils/shared.ts
=> [experiment] better fragment destructors

.prettierignore, plugins/converter.test.ts, plugins/converter.ts, plugins/utils.ts, src/components/pages/todomvc/repo.ts, src/services/router.ts, src/tests/integration/optional-chaining-paths-test.gts, src/utils/helpers/hash.ts, src/utils/reactive.ts
converting template paths from `foo.bar.baz` to `foo?.bar?.baz`
=> [feat] optional chaining in paths

src/tests/integration/cell-test.gts, src/tests/integration/each-test.gts, src/tests/integration/effect-test.gts, src/tests/integration/formula-test.gts, src/tests/integration/if-test.gts, src/tests/integration/in-element-test.gts, src/tests/integration/modifier-test.gts, src/tests/integration/slots-test.gts, src/tests/integration/yield-iterable-test.gts, src/tests/utils.ts
To match: https://rfcs.emberjs.com/id/0785-remove-set-get-in-tests/
=> [chore]: rename allSettled to rerender

src/components/pages/ToDoMVC.gts, src/components/pages/todomvc/page.gts, src/tests/integration/if-test.gts, src/utils/dom.ts, src/utils/shared.ts
=> [bugifx] yield stability in if for single text node

plugins/converter.test.ts, plugins/converter.ts, plugins/symbols.ts, src/utils/component.ts, src/utils/dom.ts, src/utils/index.ts, src/utils/shared.ts, src/utils/template.test.ts, src/utils/template.ts
=> [chore] remove not used slots prop

src/utils/dom.ts
=> [experiment] cache prop value

plugins/test.ts, src/utils/dom.ts
=> [chore] api cleanup

plugins/compiler.ts, vite.config.mts
resolves https://github.com/lifeart/glimmer-next/issues/70
=> [chore] fix prod build debug stripping

plugins/babel.ts, plugins/compiler.ts, src/utils/component.ts, src/utils/dom.ts, src/utils/helpers/hash.ts, src/utils/if.ts, src/utils/list.ts, vite.config.mts
=> [chore] improve debug stripping

plugins/flags.ts, plugins/utils.ts, src/tests/integration/slots-test.gts, src/tests/integration/yield-iterable-test.gts, src/utils/component.ts, src/utils/dom.ts, src/utils/reactive.ts, types/index.d.ts
=> [perf] try-catch flags

src/utils/list.ts
=> [chore] Improve fragment rendering

plugins/converter.test.ts, plugins/symbols.ts, plugins/utils.ts, src/utils/dom.ts
=> move forwarded props to args

src/components/pages/benchmark/Row.gts, src/utils/dom.ts, src/utils/list.ts
We keep references to generic return type for active elements inside lists and if's
In case of HMR we need to update this refs too
=> improve HMR for lists

glint-environment-gxt/-private/dsl/globals.d.ts, plugins/converter.test.ts, plugins/converter.ts, plugins/symbols.ts, src/components/Checkbox.gts, src/tests/integration/args-test.gts, src/tests/integration/input-test.gts, src/tests/integration/or-test.gts, src/tests/utils.ts, src/utils/dom.ts, src/utils/helpers/index.ts, src/utils/helpers/or.ts, src/utils/hmr.ts, src/utils/if.ts, src/utils/list.ts, src/utils/shared.ts
Improve https://github.com/lifeart/glimmer-next/issues/110
=> If reference update for hmr

src/tests/integration/let-test.gts, src/tests/utils.ts, src/utils/dom.ts, src/utils/shared.ts, src/utils/vm.ts
=> [experiment] simplify updating opcodes

src/components/pages/ToDoMVC.gts, src/components/pages/todomvc/repo.ts, src/server.ts, src/services/router.ts, src/utils/control-flow/if.ts, src/utils/dom.ts, src/utils/ssr/rehydration.ts
Attempt to fix issue, causing by https://github.com/lifeart/glimmer-next/pull/127
Working case: https://deploy-preview-125--g-next.netlify.app/todomvc
Breaking case: https://deploy-preview-127--g-next.netlify.app/todomvc
=> [wip] improve rehydration

src/tests/integration/each-test.gts, src/utils/control-flow/list.ts
For random append we need to be smarter and move only new items.
In prev implementation we always append new items at the end of list, and next items is always re-appended (and it's not working correctly xD)
Spotted while working on https://github.com/lifeart/track-it
=> [feature] improve-random-append

plugins/converter.ts, src/tests/integration/boolean-attributes-test.gts, src/tests/integration/readonly-attribute-test.gts
resolves https://github.com/lifeart/glimmer-next/issues/143
=> improve readonly support

src/tests/integration/recursive-test.gts
resolves https://github.com/lifeart/glimmer-next/issues/160
=> [chore]: nested rendering test

plugins/flags.ts, plugins/utils.ts, src/tests/integration/context-test.gts, src/tests/utils.ts, src/utils/component.ts, src/utils/context.ts, src/utils/dom.ts, src/utils/shared.ts, types/index.d.ts
attempt to implement https://github.com/lifeart/glimmer-next/issues/133
=> feature: context api

src/tests/integration/each-test.gts, src/utils/component.ts, src/utils/control-flow/list.ts, src/utils/dom.ts, src/utils/glimmer/destroyable.ts
Improvement for https://github.com/lifeart/glimmer-next/pull/150
=> [experiment] streamline element-rendering

src/utils/reactive.ts
reducing amount of checks on re-rended and removing extra variables
=> [experiment] improve memory usage

src/utils/runtime.ts
reducing amount of cleanups and checks in runtime
=> [experiment] reduce amount of checks in runtime

src/utils/dom.ts
here we removing part of forEach prior to for loop to improve memory usage
=> [experiment] improve-loops

src/utils/control-flow/list.ts
Here we adding condition to list render to avoid key set generation for new items if there is no items rendered before.
=> [experiment] improve initial list render

src/tests/integration/slots-test.gts, src/utils/dom.ts
https://github.com/lifeart/glimmer-next/issues/137
=> Add test case for default slot hiding and error handling

plugins/babel.ts, plugins/hmr.ts, src/utils/control-flow/list.ts
=> improve hmr for default exports

src/utils/control-flow/if.ts, src/utils/control-flow/list.ts, src/utils/dom.ts, src/utils/hmr.ts, src/utils/reactive.ts, src/utils/shared.ts
added state recovery after hot-reload
=> feature: hmr state recovery
